### ISSUE TITLE
Unable to start Docker image in Synology

### ISSUE THREAD

**Issue by Elfman72** [dyslexicjedi/Jorum#1]
Attempted to run this on my Synology DS1815+.

Successfully mapped a volumn variable to a share on my drive.  However, when I start the container, it exits with the following messages in the log:

```
nohup: appending output to 'nohup.out'

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.10. Set the 'ServerName' directive globally to suppress this message

Tue Apr 03 00:21:57.585181 2018] [mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.10 (Debian) PHP/7.0.28 configured -- resuming normal operations 

Tue Apr 03 00:21:57.585277 2018] [core:notice] [pid 7] AH00094: Command line: 'apache2 -D FOREGROUND' 

Tue Apr 03 00:22:16.146179 2018] [mpm_prefork:notice] [pid 7] AH00170: caught SIGWINCH, shutting down gracefully 
```
I attempted this three times with the same results. Not sure if these entires will help you at all.

Thanks again for the effort and look forward to seeing where it goes!

**Comment by dyslexicjedi** [comment]
Are you able to run it successfully without the mapping or does it exit then too?

**Comment by dyslexicjedi** [comment]
Looks like this is a known bug, possible fix is "Running docker run with --sig-proxy=false prevents SIGWINCH (and all other signals) from being sent to apache." from this thread (https://github.com/docker-library/php/issues/64). Can you please test and report?

**Comment by Elfman72** [comment]
Havne't tried the no volume mapping.  I am pretty sure it is working though since the container is dropping two SQLite files into that directory.

I will see what I can do with it and report back.  Won't be until later this weekend.  

Thanks for the info!

**Comment by Elfman72** [comment]
So this is strange.  I couldn't find this flag anywhere in my Docker settings.  So I decided to upgrade my container.  In Synology,  you simply clear out the container and it keeps any files created in the volume, and redownload the image.  Did that, ran the container and it fired up and I am able to reach the start page.  Not sure what happened there.

Going through the wizard now.  Encountering an 'Issue During Setup' at the final step.  I'll troubleshoot it some more and create another issue if I can't get it figured.

**Comment by dyslexicjedi** [comment]
It's most likely a permissions issue with the volume mount. I've been having alot of issues with that and with permissions between the backend process and the web process. It's one of the reasons for the rewrite, it should be better in the next version. 

In the mean time, please make sure the volume mount on the host is chmod'ed to 777. You can also use the debug console in chrome (f12), I believe firefox has it as well. If you watch the network tab, and look at the response from the setsettings.php page. It should say something about read-only access to the sqlite container or unable to read from the sqlite container.

**Comment by Elfman72** [comment]
Arrgh.  Now I am getting SIGWINCH errors again after shutting down the container.  Decided to rebuild my container from scratch without the Volume var and still the SIGWINCH shut down.

I'll keep tinkering with it and see what I can come up with.  So strange.

Thanks again!

**Comment by dyslexicjedi** [comment]
You may just want to wait till later in the week when v0.2 is out. The current docker is based on Apache with PHP and Python, the new version will just be a straight Python docker. So the SIGWINCH error should go away entirely. I'm actually working on it right now.

**Comment by dyslexicjedi** [comment]
Just pushed the new version, which is a rewrite to remove apache and php requirements and switch to a python only requirement. you will need to make changes to the port and volume mounts, please see the wiki or readme. You shouldn't run into any of the issues above now. Please let me know

**Comment by dyslexicjedi** [comment]
I actually pushed v0.2 this morning, spent way too much time on it this weekend. Anyways, make sure you adjust your port and volume maps to the new schema. Let me know

**Comment by Elfman72** [comment]
Just got it stood up.  Things appear to be working for now.  

What is the best way for any sort of feedback for the app?  Git?  Reddit? Elsewhere?  

Bugs will obviously go here but just things like app suggestions, changes or tweaks.

**Comment by dyslexicjedi** [comment]
Probably Reddit is the best place for feedback or suggestions. Either start a new thread or just respond to the v0.2 thread. Any feedback or suggestions would be welcomed, it's how things get better.
